apiVersion: apps/v1
kind: Deployment
metadata:
  name: arpit-1645386
  labels:
    app: spring
spec:
  replicas: 1
  selector:
       matchLabels:
         app: spring
  template:
    metadata:
      name: spring
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: arpit74/testing:first
        resources:
          limits:
            memory: 1Gi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
  selector:
    matchLabels:
      app: spring

---

apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  selector:
    app: spring
  ports:
    - port: 8080
  type: LoadBalancer
